CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS todo_list (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    done BOOLEAN DEFAULT false,
    created_by INTEGER REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO todo_list (title, done) 
VALUES ('Setup Docker + PostgreSQL', true)
ON CONFLICT DO NOTHING;
